### ISSUE TITLE
Language overrides

### ISSUE THREAD

**Issue by devopsgws** [hexonet/whmcs-ispapi-domainchecker#178]
Hi, we'd like to use the folder `ispapidomaincheck/lang/overrides/` to add our modifications to the language files, as is common with addons.

The domainchecker would have to check for files there and use them if they exist.

Could this be included?

**Comment by KaiSchwarz-cnic** [comment]
Hi @devopsgws 

sorry for the delay. We were busy with our repository merger (find our domainchecker also now continued there):
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs

We will give you feedback asap regarding your question.

Kai

**Comment by KaiSchwarz-cnic** [comment]
Hi @devopsgws 

Support for language overrides has been added.
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v16.5.0

Still, let me also forward that we don't consider the whmcs way of supporting language override files for addons as perfect way, but there's no alternative if we follow their design.
Whenever it is about upgrading, we ask resellers to first delete our folders to ensure all module files are getting cleaned up. Otherwise some deprecated PHP classes could be left on hard disk and still getting auto-loaded by whmcs and leading to PHP errors in worst case. The deletion of folders would then also include the deletion of the language overrides folder.
That means, whenever upgrading, please ensure to backup the language overrides before doing the cleanup.

HTH
Kai
